USE weconnect;

ALTER TABLE USERS ADD COLUMN job_title VARCHAR(255) NULL;
ALTER TABLE USERS ADD COLUMN education VARCHAR(255) NULL;
ALTER TABLE USERS ADD COLUMN relationship_status VARCHAR(50) NULL;
